// lv_conf.h — minimal LVGL v9 config for the DESKTOP SIMULATOR only.
// (The device build configures LVGL via ESP-IDF Kconfig, not this file.)
// Unspecified options fall back to lv_conf_internal.h defaults.
#ifndef LV_CONF_H
#define LV_CONF_H

#ifndef __ASSEMBLY__
#include <stdint.h>
#endif

#define LV_COLOR_DEPTH 32

// use the C standard library for mem/str/printf on desktop
#define LV_USE_STDLIB_MALLOC  LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING  LV_STDLIB_CLIB
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_CLIB

// Fonts: the UI uses bundled Inter (ui/inter_*.c, generated by
// scripts/gen_fonts.sh) — no LVGL built-in Montserrat. The LVGL default font
// is the smallest Inter cut; styles.h sets the per-role fonts explicitly.
#define LV_FONT_CUSTOM_DECLARE LV_FONT_DECLARE(inter_regular_12)
#define LV_FONT_DEFAULT &inter_regular_12

// SDL window backend
#define LV_USE_SDL 1
#define LV_SDL_INCLUDE_PATH <SDL2/SDL.h>

#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN

#endif // LV_CONF_H
