// styles.h — centralized design tokens (SPEC-ytmusic-now-playing.md §5)
//
// One source of truth for the theme. A dark/AMOLED variant later is a swap of
// these values, not a rewrite. NO ad-hoc colors anywhere else in the UI.
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// ---- Color tokens (cream / warm theme) ----
#define COL_BG        lv_color_hex(0xFBF7F3)  // warm cream — app background
#define COL_BG2       lv_color_hex(0xFFFFFF)  // cards / raised surfaces
#define COL_INK       lv_color_hex(0x1A1410)  // primary text
#define COL_INK2      lv_color_hex(0x4A3F37)  // secondary text
#define COL_INK3      lv_color_hex(0x8A7A6E)  // muted / meta
#define COL_INK4      lv_color_hex(0xB8A99A)  // faint / placeholders / icons
#define COL_LINE      lv_color_hex(0xECE2D8)  // borders / dividers
#define COL_DANGER    lv_color_hex(0xC0392B)  // destructive / error only

// Brand gradient stops (135°): indigo -> purple -> pink
#define COL_INDIGO    lv_color_hex(0x6366F1)  // gradient start
#define COL_PURPLE    lv_color_hex(0xA855F7)  // secondary accent (play, dots, ★)
#define COL_PINK      lv_color_hex(0xEC4899)  // primary interactive accent

// ---- Radii ----
#define RAD_PILL      LV_RADIUS_CIRCLE
#define RAD_CARD      16
#define RAD_COVER     20

// ---- Fonts ----
// Slice uses LVGL built-in Montserrat. Production swaps in bundled Inter
// ExtraBold/800 (see README "Fonts"). Roles map 1:1 onto the spec's type scale.
#define FONT_LABEL    (&lv_font_montserrat_12)  // section labels 11px/800 uppercase
#define FONT_TITLE    (&lv_font_montserrat_28)  // display title 800
#define FONT_BODY     (&lv_font_montserrat_16)  // body ~15px
#define FONT_META     (&lv_font_montserrat_14)  // meta / caption
#define FONT_ICON     (&lv_font_montserrat_22)  // transport glyphs (fallback)

// ---- Material Symbols icon fonts (generated by scripts/gen_icons.sh) ----
// mdi_solid: FILL 1 @30px — transport + filled thumb_up
// mdi_line:  FILL 0 @26px — outline thumb_up / thumb_down
LV_FONT_DECLARE(mdi_solid);
LV_FONT_DECLARE(mdi_line);
#define FONT_ICONS       (&mdi_solid)
#define FONT_ICONS_LINE  (&mdi_line)

// UTF-8 byte sequences for each Material Symbols codepoint.
#define IC_PREV    "\xEE\x81\x85"  // U+E045 skip_previous
#define IC_NEXT    "\xEE\x81\x84"  // U+E044 skip_next
#define IC_PLAY    "\xEE\x80\xB7"  // U+E037 play_arrow
#define IC_PAUSE   "\xEE\x80\xB4"  // U+E034 pause
#define IC_LIKE    "\xEE\xA3\x9C"  // U+E8DC thumb_up
#define IC_DISLIKE "\xEE\xA3\x9B"  // U+E8DB thumb_down

#ifdef __cplusplus
}
#endif
