// styles.h — centralized design tokens (SPEC-ytmusic-now-playing.md §5)
//
// One source of truth for the theme. The dark/light split is a token swap, not a
// rewrite: every role below is defined once per theme block. NO ad-hoc colors
// anywhere else in the UI.
#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

// ---- Build-time theme selection ----
// Dark (V2 default, near-black/AMOLED) is the default AND the fallback in BOTH
// build systems. Light is the same layout painted with light tokens and the
// album glow disabled. There is no runtime toggle.
//   - Firmware: a Kconfig `choice` sets CONFIG_YTM_THEME_LIGHT when Light is picked
//     (see firmware/main/Kconfig.projbuild). Default leaves it dark.
//   - Desktop sim: pass -DYTM_THEME_LIGHT (e.g. `cmake -B build -DYTM_THEME=LIGHT`).
// Anything else — including no define at all — resolves to Dark.
#if defined(CONFIG_YTM_THEME_LIGHT) || defined(YTM_THEME_LIGHT)
#  define THEME_IS_LIGHT 1
#else
#  define THEME_IS_LIGHT 0
#endif

// Album-derived ambient glow is a Dark-only feature; Light paints flat (no glow).
// The renderer (later slice) checks this flag before building the glow canvas.
#if THEME_IS_LIGHT
#  define THEME_AMBIENT_ENABLED 0
#else
#  define THEME_AMBIENT_ENABLED 1
#endif

// ---- Color tokens ----
#if THEME_IS_LIGHT
// ===== Light theme (cream / warm) — V2 layout, light tokens, glow disabled =====
#define COL_BG        lv_color_hex(0xFBF7F3)  // warm cream — app background
#define COL_BG2       lv_color_hex(0xFFFFFF)  // cards / raised surfaces
#define COL_INK       lv_color_hex(0x1A1410)  // primary text
#define COL_INK2      lv_color_hex(0x4A3F37)  // secondary text
#define COL_INK3      lv_color_hex(0x8A7A6E)  // muted / meta
#define COL_INK4      lv_color_hex(0xB8A99A)  // faint / placeholders / icons
#define COL_LINE      lv_color_hex(0xECE2D8)  // borders / dividers
#define COL_DANGER    lv_color_hex(0xC0392B)  // destructive / offline accent
#define COL_STRIPE    lv_color_hex(0xF3EADF)  // cover placeholder fill
#define COL_ON_ACCENT lv_color_hex(0xFFFFFF)  // glyph/text drawn on an accent fill

// Brand gradient stops (135°): indigo -> purple -> pink
#define COL_INDIGO    lv_color_hex(0x6366F1)  // gradient start
#define COL_PURPLE    lv_color_hex(0xA855F7)  // secondary accent (play, dots, ★)
#define COL_PINK      lv_color_hex(0xEC4899)  // primary interactive accent
#else
// ===== Dark theme (default) — near-black / AMOLED =====
#define COL_BG        lv_color_hex(0x070709)  // near-black — app background
#define COL_BG2       lv_color_hex(0x121215)  // cards / raised surfaces (banner)
#define COL_INK       lv_color_hex(0xFFFFFF)  // primary text (white)
#define COL_INK2      lv_color_hex(0xB7B7BB)  // secondary text (~white .72)
#define COL_INK3      lv_color_hex(0x949499)  // muted / meta (~white .55)
#define COL_INK4      lv_color_hex(0x6A6A6E)  // faint / placeholders / icons (~white .4)
#define COL_LINE      lv_color_hex(0x2A2A2D)  // borders / dividers (~white .12)
#define COL_DANGER    lv_color_hex(0xFF6B6B)  // offline accent
#define COL_STRIPE    lv_color_hex(0x16161A)  // cover placeholder fill (raised dark)
#define COL_ON_ACCENT lv_color_hex(0xFFFFFF)  // glyph/text drawn on an accent fill

// Accent stops. The primary interactive accent is the V2 red (#FF4458); the
// indigo/purple stops keep the multi-stop gradient on slider/play/cover.
#define COL_INDIGO    lv_color_hex(0x6366F1)  // gradient start
#define COL_PURPLE    lv_color_hex(0xA855F7)  // secondary accent (play, dots, ★)
#define COL_PINK      lv_color_hex(0xFF4458)  // primary interactive accent (red)
#endif

// ---- Radii ----
#define RAD_PILL      LV_RADIUS_CIRCLE
#define RAD_CARD      16
#define RAD_COVER     20

// ---- Fonts (bundled Inter, generated by scripts/gen_fonts.sh) ----
// Inter at the V2 type scale, replacing the Montserrat placeholders. Roles map
// 1:1 onto the spec's type scale (weights from NowPlayingDeviceV2.dc.html); the
// V2 weight set is Regular / SemiBold 600 / ExtraBold 800 — 900 is not bundled,
// 800 suffices at panel scale.
LV_FONT_DECLARE(inter_extrabold_29);
LV_FONT_DECLARE(inter_extrabold_12);
LV_FONT_DECLARE(inter_semibold_17);
LV_FONT_DECLARE(inter_semibold_13);
LV_FONT_DECLARE(inter_semibold_12);
LV_FONT_DECLARE(inter_regular_12);
#define FONT_TITLE    (&inter_extrabold_29)  // display title 29 / 800
#define FONT_LABEL    (&inter_extrabold_12)  // status row 12 / 800 uppercase
#define FONT_BODY     (&inter_semibold_17)   // artist 17 / 600
#define FONT_META     (&inter_semibold_13)   // album 13 / 600
#define FONT_TIME     (&inter_semibold_12)   // elapsed / total 12 / 600
#define FONT_ICON     (&inter_semibold_17)   // transport glyph text fallback

// ---- Material Symbols icon fonts (generated by scripts/gen_icons.sh) ----
// mdi_solid: FILL 1 @30px — transport + filled thumb_up + music_note
// mdi_line:  FILL 0 @26px — outline thumb_up / thumb_down
LV_FONT_DECLARE(mdi_solid);
LV_FONT_DECLARE(mdi_line);
#define FONT_ICONS       (&mdi_solid)
#define FONT_ICONS_LINE  (&mdi_line)

// UTF-8 byte sequences for each Material Symbols codepoint.
#define IC_PREV    "\xEE\x81\x85"  // U+E045 skip_previous
#define IC_NEXT    "\xEE\x81\x84"  // U+E044 skip_next
#define IC_PLAY    "\xEE\x80\xB7"  // U+E037 play_arrow
#define IC_PAUSE   "\xEE\x80\xB4"  // U+E034 pause
#define IC_LIKE    "\xEE\xA3\x9C"  // U+E8DC thumb_up
#define IC_DISLIKE "\xEE\xA3\x9B"  // U+E8DB thumb_down
#define IC_MUSIC   "\xEE\x90\x85"  // U+E405 music_note (ad / empty cover block)

#ifdef __cplusplus
}
#endif
